# This workflow should trigger everytime a branch is pushed to remote, it will test that your commit
# runs and that all tests pass
name: Build and Test

on:
  push:
    branches:
      - "**"

jobs:

  check-lint:
    environment: verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Using node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci
      - run: npm run lint

  unit-test:
    environment: verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Using node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci
      - run: npm run unit-test

  build-android-dev:
    environment: build
    runs-on: ubuntu-latest
    needs: [check-lint, unit-test]

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - run: npm ci
      - run: eas build --platform android --local --profile dev --non-interactive