# This workflow should trigger everytime a branch is pushed to remote and a pull request is open for that branch
name: Build

on:
  push:
    branches:
      - main

jobs:
  build-android-dev:
    environment: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
          eas-cache: true

      - run: npm ci
      - run: eas build --platform android --local --profile dev --non-interactive --output android_dev.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
            name: android_dev
            path: /home/runner/work/app_core/app_core/android_dev.apk

  build-android-preview:
    environment: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
          eas-cache: true

      - run: npm ci
      - run: eas build --platform android --local --profile preview --non-interactive --output android_preview.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android_preview
          path: /home/runner/work/app_core/app_core/android_preview.apk