# This workflow should trigger everytime a branch is pushed to remote.
name: Build

on:
  push:

jobs:
  check-lint:
    environment: verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Using node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci
      - run: npm run lint

  unit-test:
    environment: verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Using node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci
      - run: npm run unit-test